version: "3.9"

services:
  web:
    build: .
    command: conda run --no-capture-output -n eTransafeEnv python manage.py runserver 0.0.0.0:8000 #by default it runs with local profile (settings.local)
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"

