"""
Django settings for chemistry_services_project project.

Generated by 'django-admin startproject' using Django 3.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""
import os
from datetime import date, datetime
from pathlib import Path
from decouple import config


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config("SECRET_KEY")


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

INITIAL_ALLOWED_HOSTS = ['127.0.0.1', 'localhost']
# Application definition
ALLOWED_HOSTS = INITIAL_ALLOWED_HOSTS if "ADDITIONAL_ALLOWED_HOSTS" not in os.environ else list(set(INITIAL_ALLOWED_HOSTS + os.environ.get("ADDITIONAL_ALLOWED_HOSTS").split(' ')))
if "ADDITIONAL_ALLOWED_HOSTS" in os.environ:
    print("ADDITIONAL_ALLOWED_HOSTS SET IN OS_ENVIRON")
    print(ALLOWED_HOSTS)
else:
    print("ADDITIONAL_ALLOWED_HOSTS NOT SET IN OS_ENVIRON")
    print(ALLOWED_HOSTS)

APPEND_SLASH = False

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'chemistry_services_app.apps.ChemistryServicesAppConfig',
    #'drf_yasg',
    'drf_spectacular',
]

REST_FRAMEWORK = {
    # YOUR SETTINGS
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_METADATA_CLASS': 'rest_framework.metadata.SimpleMetadata'
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'eTransafe Chemistry Services',
    'DESCRIPTION': 'ChEMBL protocols used to standardise and salt strip molecules. First used in ChEMBL 26',
    'VERSION': '1.0.10',
    'CONTACT': {
                'name': 'Tevfik Kiziloren',
                'url': 'https://www.ebi.ac.uk/chembl',
                'email': 'tevfik@ebi.ac.uk'
               },
    'API_VERSION': 'v1',
    'DEFAULT_VERSION': 'v1',
    'SERVERS': [
        {
            'url': '/v1',
            'description': 'Base URL of the API'
        }
    ],
    'EXTENSIONS_INFO': {
        'termsOfService': 'https://github.com/chembl/ChEMBL_Structure_Pipeline',
        'x-meta': {
            'serviceType': 'aggregator',
            'uuid': 'bd21f81f-d975-4fbb-a4bd-c1af6b8477d8',
            'provider': 'EMBL-EBI',
            'created': datetime.strptime("24052021", "%d%m%Y").date(),
            'released': datetime.strptime("24052021", "%d%m%Y").date(),
            'lastChanged': datetime.strptime("01062021", "%d%m%Y").date(),
            'software': [
                {
                    'name': 'Chemistry Service',
                    'version': '1.0',
                    'description': 'eTransafe Chemistry Services',
                    'provider': 'EMBL-EBI',
                    'license': {
                        'name': 'EMBL-EBI',
                        'url': 'https://www.ebi.ac.uk/chembl'
                    }
                }
            ]
        },
    },
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

CONFIG_DIR = os.path.join(os.path.dirname(__file__), os.pardir)

# Excempt list - URL paths that doesn't need Keycloak Authorization
KEYCLOAK_BEARER_AUTHENTICATION_EXEMPT_PATHS = [
    'schema', 'doc', 'redoc', 'doc.yaml', '/doc.yaml', 'doc.yaml/', '/doc.yaml', 'api-spec/', '/api-spec/', 'api-spec', 'v1/api', 'v1/alive', 'v1/ready', 'api/v1/api', 'api/v1/alive', 'api/v1/ready',
]


ROOT_URLCONF = 'chemistry_services_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'chemistry_services_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    },
    'chembl_mysql': {

    }

}

# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

LOGGING = {
    'version': 1,
    # Version of logging
    'disable_existing_loggers': False,

    'filters': {
        # information regarding filters
    },

    'formatters': {
        'default': {
            'format': '[DJANGO] %(levelname)s %(asctime)s %(module)s '
                      '%(name)s.%(funcName)s:%(lineno)s: %(message)s'
        },
    },

    'handlers': {
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'default',
        },
    },

    'loggers': {
        '*': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': True,
        }
    },
}

# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = '/static/'

